"""Local project memory — the offline analog of Claude Code's CLAUDE.md.

`local init` walks the repo with the same funnel the agent uses and writes
`local_mind.md`, a concise, grounded orientation document. Every later query
injects that doc as project context (see loop.run_turn), so the agent starts
oriented instead of re-deriving the layout each turn.

A machine-readable fingerprint of the source tree is kept in a sidecar file
(`.local_mind.sig.json`) so we can tell when the code has changed *enough* to be
worth regenerating — without bloating the human-readable doc.

Stdlib only, fully local, no network.
"""

import hashlib
import json
import os
import re
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from . import config

MIND_FILENAME = "local_mind.md"
SIG_FILENAME = ".local_mind.sig.json"
INIT_MAX_TURNS = 60  # a whole-repo walk needs many tool calls

# Directories that never carry project signal (kept in sync with the tools).
_SKIP_DIRS = {
    ".git", ".hg", ".svn", ".bzr", ".jj", ".sl", "node_modules",
    ".venv", "venv", "env", "__pycache__", ".mypy_cache", ".pytest_cache",
    ".ruff_cache", ".tox", "dist", "build", "target", ".agent-backups",
    ".idea", ".vscode",
}
# Only fingerprint files that look like source/config, so a changed data blob or
# image doesn't read as "the code changed". Extensionless well-knowns included.
_CODE_EXTS = {
    ".py", ".pyi", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".go", ".rs",
    ".java", ".c", ".h", ".cc", ".cpp", ".hpp", ".hh", ".cxx", ".rb", ".php",
    ".cs", ".kt", ".swift", ".scala", ".m", ".mm", ".sh", ".bash", ".ps1",
    ".sql", ".html", ".css", ".scss", ".vue", ".svelte", ".toml", ".ini",
    ".cfg", ".yaml", ".yml", ".json", ".md", ".txt", ".gradle", ".mk",
    "Makefile", "Dockerfile",
}
_MAX_FILES = 20000  # safety cap for the walk


def _is_code(name):
    if name in _CODE_EXTS:  # extensionless well-knowns (Makefile, Dockerfile)
        return True
    return os.path.splitext(name)[1].lower() in _CODE_EXTS


# Our own generated artifacts must not count toward the fingerprint, or a freshly
# written map would instantly look "changed" (local_mind.md is .md, the sidecar .json).
_OWN_FILES = {MIND_FILENAME, SIG_FILENAME}


def _walk_files(root):
    """{rel_path: size} for every source/config file under root, skipping junk."""
    root = Path(root)
    files = {}
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in _SKIP_DIRS]
        for fn in filenames:
            if fn in _OWN_FILES:
                continue
            if not _is_code(fn):
                continue
            p = Path(dirpath) / fn
            try:
                rel = str(p.relative_to(root)).replace("\\", "/")
                files[rel] = p.stat().st_size
            except (OSError, ValueError):
                continue
            if len(files) >= _MAX_FILES:
                return files
    return files


def _hash_files(files):
    joined = "\n".join(f"{p}\t{s}" for p, s in sorted(files.items()))
    return hashlib.sha256(joined.encode("utf-8", "replace")).hexdigest()


def _count_changed(old, new):
    return sum(1 for k in set(old) | set(new) if old.get(k) != new.get(k))


def _git_head(root):
    try:
        out = subprocess.run(
            ["git", "-C", str(root), "rev-parse", "HEAD"],
            capture_output=True, text=True, timeout=10,
        )
        if out.returncode == 0:
            return out.stdout.strip() or None
    except Exception:
        pass
    return None


def signature(root):
    files = _walk_files(root)
    return {
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "git_head": _git_head(root),
        "file_count": len(files),
        "total_bytes": sum(files.values()),
        "files_hash": _hash_files(files),
        "files": files,
    }


def mind_path(root):
    return Path(root) / MIND_FILENAME


def _sig_path(root):
    return Path(root) / SIG_FILENAME


def save(root, content):
    """Write local_mind.md (the doc) + its signature sidecar. Returns (path, sig)."""
    root = Path(root)
    sig = signature(root)
    doc = (content or "").strip() + "\n"
    header = (
        f"<!-- generated by `local init` on {sig['generated_at']} · "
        f"git {(sig['git_head'] or 'n/a')[:12]} · {sig['file_count']} files scanned. "
        f"Regenerate with /init (or `local init`) after big changes; do not hand-edit "
        f"the sidecar {SIG_FILENAME}. -->\n\n"
    )
    mind_path(root).write_text(header + doc, encoding="utf-8")
    _sig_path(root).write_text(json.dumps(sig), encoding="utf-8")
    return mind_path(root), sig


_HDR_RE = re.compile(r"^\s*<!--.*?-->\s*", re.DOTALL)


def _strip_header(text):
    return _HDR_RE.sub("", text, count=1)


def read_mind(root):
    """The doc text (leading comment header stripped), or None if absent/empty."""
    try:
        text = mind_path(root).read_text(encoding="utf-8", errors="replace")
    except (OSError, FileNotFoundError):
        return None
    text = _strip_header(text).strip()
    return text or None


def mind_context(root):
    """The doc, capped to config.MIND_CONTEXT_CAP chars, ready to inject as context."""
    if root is None:
        return ""
    doc = read_mind(root)
    if not doc:
        return ""
    cap = config.MIND_CONTEXT_CAP
    if len(doc) > cap:
        doc = doc[:cap].rstrip() + "\n\n… (local_mind.md truncated for context; full file is on disk)"
    return doc


def is_stale(root):
    """(stale: bool, reason: str).

    'Stale' means the source tree changed *enough* to be worth regenerating —
    files added/removed/resized past an absolute or proportional threshold, or the
    git HEAD moved with any accompanying code change. A missing/​unreadable sidecar
    returns (False, "") because we can't tell, so we never nag without evidence.
    """
    try:
        old = json.loads(_sig_path(root).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return False, ""
    cur_files = _walk_files(root)
    if old.get("files_hash") and _hash_files(cur_files) == old["files_hash"]:
        return False, ""  # byte-identical tree — definitely not stale
    old_files = old.get("files") or {}
    changed = _count_changed(old_files, cur_files)
    old_n = max(1, old.get("file_count", len(old_files)))
    head_moved = bool(old.get("git_head")) and _git_head(root) not in (None, old.get("git_head"))
    massive = (
        changed >= config.MIND_STALE_FILES
        or (changed / old_n) >= config.MIND_STALE_RATIO
        or (head_moved and changed >= 1)
    )
    if not massive:
        return False, ""
    reason = (
        f"{changed} source file(s) changed since it was generated "
        f"({old.get('file_count', '?')} → {len(cur_files)} files)"
    )
    return True, reason


# --- the `local init` exploration prompt ------------------------------------
# Overrides DEFAULT_INSTRUCTIONS for the init run: same funnel + grounding, but it
# must emit a Markdown document (not terminal plain text), and the FINAL answer is
# taken verbatim as the file contents.
INIT_INSTRUCTIONS = (
    "You are creating `local_mind.md` — a concise orientation document for THIS "
    "repository,  that a new engineer (or an "
    "AI agent) reads to get oriented fast. Investigate the codebase with the tools "
    "(`list_dir` to orient, `glob` to locate, `grep` to find definitions, `read` to "
    "confirm) and ground EVERY statement in what the tools actually return — never "
    "guess, and never rely on memory of a similarly-named project; the code in THIS "
    "repo may differ.\n\n"
    "Cover these as sections, but only what you can actually verify:\n"
    "1. Overview — what the project is and does, and its main language(s).\n"
    "2. Setup & commands — the real build / run / test / lint commands (from README, "
    "package.json scripts, Makefile, pyproject.toml, etc.). Quote them exactly.\n"
    "3. Architecture — the big picture: the major components, how they fit together, "
    "and how control/data flows between them (the part that needs reading several "
    "files, not just a directory listing).\n"
    "4. Key directories & modules — the important ones and each one's responsibility.\n"
    "5. Entry points — where execution starts (CLI, server, main).\n"
    "6. Conventions & patterns — naming, error handling, testing style, notable idioms.\n"
    "7. Gotchas — non-obvious constraints a new contributor would trip on.\n\n"
    "Keep it high-signal and reasonably short (roughly 60–200 lines). Cite paths "
    "(and line ranges where useful). Omit any section you genuinely cannot verify.\n\n"
    "OUTPUT FORMAT: your FINAL answer must be the COMPLETE contents of local_mind.md "
    "and nothing else — start directly with a top-level '# ' heading. Use plain "
    "GitHub Markdown (headings, bullets, fenced code blocks for commands). Do NOT "
    "wrap the whole document in a code fence, and do NOT add any commentary before or "
    "after it."
)

INIT_PROMPT = (
    "Run `local init`: analyze this entire repository and produce local_mind.md as "
    "specified. Start by orienting yourself at the project root, then dig into the "
    "important modules and how they connect. When you understand the project well "
    "enough, output the final document."
)
